package com.example.cataniaunited.dto;

public enum MessageType {

    //Server Messages
    CONNECTION_SUCCESSFUL,
    CLIENT_DISCONNECTED,
    ERROR,
    LOBBY_UPDATED,
    PLAYER_JOINED,
    LOBBY_CREATED,
    GAME_WON,
    GAME_BOARD_JSON,
    GAME_STARTED,
    DICE_RESULT,
    NEXT_TURN,
    PLAYER_RESOURCE_UPDATE,

    //Client Messages
    CREATE_LOBBY,
    JOIN_LOBBY,
    LEAVE_LOBBY,
    SET_USERNAME,
    START_GAME,
    PLACE_SETTLEMENT,
    UPGRADE_SETTLEMENT,
    PLACE_ROAD,
    ROLL_DICE,
    END_TURN,
    SET_READY,
    TRADE_WITH_BANK,
    CHEAT_ATTEMPT,
    REPORT_PLAYER

}